### ISSUE TITLE
Error with: yo ui-component:internal

### ISSUE THREAD

**Issue by manifestinteractive** [holidayextras/generator-ui-component#9]
Getting an error when I run the following in terminal:

```bash
cd ./ui-toolkit/src/components
yo ui-component:internal 
```

```
Building view within project ui-toolkit
Error ui-component:internal

Current project is not in expected format (no code/ directory in project root /Volumes/Storage/Holiday Extras/ui-toolkit/)
```

When I asked @jackdcrawford, he mentioned:

that's a known issue i believe, __luke__ mentioned it before, we need to modify the generator so that it doesn't require `code/` to be there

**Comment by lukehansell** [comment]
does anyone currently use the generator? I believe we've agreed to not bother as making component framework is trivial and people could do with understanding the background. Closing this until someone disagrees.
